services:
  redis:
    container_name: RedisCache
    image: redis:latest
    ports:
      - "6379:6379"
  mongo:
    container_name: MongoDatabase
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=pass
    restart: on-failure
    ports:
      - "27017:27017"