spring:
  application:
    name: url-registry
  cache:
    type: redis
    redis:
      time-to-live: 5
  data:
    mongodb:
      username: mongo
      password: pass
      authentication-database: admin
      port: 27017
      database: full_url_database
    redis:
      host: localhost
      port: 6379
server:
  port: 8083