spring:
  application:
    name: shortcut-registry
  cache:
    type: redis
    redis:
      time-to-live: 10
  data:
    mongodb:
      username: mongo
      password: pass
      authentication-database: admin
      port: 27017
      database: shortcut_database
    redis:
      host: localhost
      port: 6379

server:
  port: 8081